### ISSUE TITLE
Test Dashboard Functionality

### ISSUE THREAD

**Issue by rebeccahendsey** [rebeccahendsey/trend-stats#10]
# Description 

Conductive comprehensive testing of the dashboard to ensure seamless usability and functionality. 
 
# To-Do:

- [ ] Verify all interactive features work as expected 
- [ ] Perform compatibility testing for various browsers (ex. Chrome, Firefox, etc.) and screen sizes
- [ ] Ensure data accuracy 
- [ ] Check speed and performance 
- [ ] Ensure ease of navigation
- [ ] Check for error handling and edge cases

# Acceptance Criteria: 

- [ ] Everything works as expected
- [ ] Document issues as needed
