### ISSUE TITLE
Perform Statistical Analysis

### ISSUE THREAD

**Issue by rebeccahendsey** [rebeccahendsey/trend-stats#6]
# Description 

Extract & prepare the cleaned & analyzed data for visualization in the dashboard. Use insights from issue #5 to determine what data to include. This issue uses the original, cleaned data and the insight from step #5. The output is a csv file with all relevant variables, calculations (mean, median, variance, standard deviation, etc.), and insights derived. 

# To-Do: 

- [ ] Extract relevant data from the cleaned datasets
- [ ] Aggregate or summarize data as needed for visualization 
- [ ] Ensure data is in an appropriate format for dashboard integration (use CSV for Tableau)
