### ISSUE TITLE
Dashboard Design and Layout

### ISSUE THREAD

**Issue by rebeccahendsey** [rebeccahendsey/trend-stats#7]
# Description 

Design the layout and structure of the dashboard using Tableau to effectively communication insights and trends derived from the data analysis.

# To-Do:

- [ ] Plan the layout and structure (may require discovery)
- [ ] Select appropriate visuals 
- [ ] Choose a color scheme and styling

# Acceptance Criteria: 

- [ ] A Tableau workbook is created and uses the designed dashboard layout and visualizations
